version = 1

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "cxx"
enabled = true

[[analyzers]]
name = "rust"
enabled = true

  [analyzers.meta]
  msrv = "nightly"

[[transformers]]
name = "rustfmt"
enabled = true